# Generated by Django 5.2 on 2025-05-14 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_date_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, default='users/default.png', null=True, upload_to='users/%Y/%m/%d/', verbose_name='Фотография'),
        ),
    ]
