# Generated by Django 5.2 on 2025-05-14 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product_Ozon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.BigIntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('brand', models.CharField(blank=True, max_length=100, null=True)),
                ('review_rating', models.FloatField(blank=True, null=True)),
                ('feedbacks', models.IntegerField(blank=True, null=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('price_product', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_basic', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('supplier_id', models.BigIntegerField(blank=True, null=True)),
                ('supplier_rating', models.FloatField(blank=True, null=True)),
                ('pics', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Product_WB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.BigIntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('brand', models.CharField(blank=True, max_length=100, null=True)),
                ('review_rating', models.FloatField(blank=True, null=True)),
                ('feedbacks', models.IntegerField(blank=True, null=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('price_product', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_basic', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('supplier_id', models.BigIntegerField(blank=True, null=True)),
                ('supplier_rating', models.FloatField(blank=True, null=True)),
                ('pics', models.IntegerField(default=0)),
                ('first_image_path', models.CharField(blank=True, max_length=510, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
