# Generated by Django 5.2 on 2025-05-12 14:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_product_wb_rename_product_product_ozon'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_wb',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product_wb',
            name='first_image_path',
            field=models.CharField(blank=True, max_length=510, null=True),
        ),
        migrations.AddField(
            model_name='product_wb',
            name='pics',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product_wb',
            name='supplier_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product_wb',
            name='supplier_rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
